#!/usr/bin/with-contenv bash

# Create uploads directory if not exists
if [ ! -d $UPLOADS_ROOT ] ; then
  mkdir -p $UPLOADS_ROOT
fi

chown wordpress:web $UPLOADS_ROOT

# Create log directory
mkdir -p /var/log/nginx

# Create dir for sessions and cache
mkdir -p /tmp/nginx
chown wordpress:web /tmp/nginx

# Create log directory for php
mkdir -p /var/log/php/
touch /var/log/php/error.log
chown -R wordpress:web /var/log/

# Create directory for mail logs
mkdir -p /var/log/mail
chown wordpress:web /var/log/mail
