#!/usr/bin/with-contenv bash
##
# Php uses msmtp binary to send email
# This script changes /etc/msmtprc settings to change the used server
# Typically you can configure 1 postfix which can send email from all containers
##

# msmtp is really picky and won't run if permissions are not set correctly
chown wordpress:web /etc/msmtprc
chmod 0600 /etc/msmtprc

# Replace msmtp 'from' field
if [ -n "$SMTP_FROM" ]; then

  sed -i "s/^from.*$/from $SMTP_FROM/g" /etc/msmtprc

elif [ -n "$MAIL_DOMAIN" ]; then

  sed -i "s/^from.*$/from no-reply@$MAIL_DOMAIN/g" /etc/msmtprc

elif wp core is-installed; then

  # If SMTP_FROM was not setupped try to ask the domain from wordpress
  # Also remove 'www.' if any
  smtp_from=no-reply@"$(wp option get siteurl | sed 's/https\?:\/\///' | sed 's/^www.//')"
  sed -i "s/^from.*$/from $smtp_from/g" /etc/msmtprc

elif [ -n "$WP_HOME" ]; then

  # If SMTP_FROM was not setupped and wordpress is not installed/ready use WP_HOME variable
  # Also remove 'www.' if any
  smtp_from=no-reply@"$(echo $WP_HOME | sed 's/https\?:\/\///' | sed 's/^www.//')"
  sed -i "s/^from.*$/from $smtp_from/g" /etc/msmtprc

fi

# Replace msmtp 'host' field
if [ -n "$SMTP_HOST" ]; then
  sed -i "s/^host .*$/host $SMTP_HOST/g" /etc/msmtprc
fi

# Replace msmtp 'port' field
if [ -n "$SMTP_PORT" ]; then
  sed -i "s/^port .*$/port $SMTP_PORT/g" /etc/msmtprc
fi

# Replace msmtp 'tls' field, possible fields on/off
if [ -n "$SMTP_TLS" ]; then
  sed -i "s/^tls .*$/tls on/g" /etc/msmtprc
fi

# Use user for authenticating if it's provided
if [ -n "$SMTP_USER" ]; then
  sed -i "s/^#user .*$/user $SMTP_USER/g" /etc/msmtprc
fi

# Use password for authenticating if it's provided
if [ -n "$SMTP_PASSWORD" ]; then
  sed -i "s/^#password .*$/password $SMTP_PASSWORD/g" /etc/msmtprc
fi

# Replace msmtp 'auth' field when provided
# And also when both password and username are given
if [ -n "$SMTP_AUTH" ]; then
  sed -i "s/^auth .*$/auth on/g" /etc/msmtprc
fi
