#!/usr/bin/with-contenv bash

# Set xdebug remote from docker env
if [ -n "$XDEBUG_REMOTE_HOST" ]; then
    echo "xdebug.remote_host=$XDEBUG_REMOTE_HOST" > /etc/php7/conf.d/xdebug_remote.ini
fi

# Change ownership of xdebug folder to web user
chown wordpress:web /tmp/xdebug/
