#!/usr/bin/with-contenv sh
##
# This script uses clever heredoc hack to substitute env variables into static config files
# Source: http://stackoverflow.com/questions/2914220/bash-templating-how-to-build-configuration-files-from-templates-with-bash
##

echo "INFO: Substituting env into configuration files..."
# render a template configuration file to temporary file and replace the original file
# This substitutes ${PORT} style notations
# expand variables + preserve formatting
render_template() {
    filename=$(basename $1)
    eval "echo \"$(cat $1)\"" > /tmp/$filename
    mv /tmp/$filename $1
}

# Nginx doesn't support env variables in config files so we will have to do this in hacky way instead
render_template /etc/nginx/nginx.conf
