#!/usr/bin/with-contenv bash

# Copy cronjob from project and run as nginx
if [ -f $PROJECT_ROOT/tasks.cron ]; then
    cp $PROJECT_ROOT/tasks.cron /var/spool/cron/crontabs/$WEB_USER
else
    # No cronjobs found remove crond from s6
    if [ -f /etc/services.d/crond ]; then
        rm -r /etc/services.d/crond
    fi
fi
