#!/usr/bin/with-contenv bash

# Create uploads directory if not exists
if [ ! -d $UPLOADS_ROOT ] ; then
  mkdir -p $UPLOADS_ROOT
fi

chown $WEB_USER:$WEB_GROUP $UPLOADS_ROOT

# Create dir for nginx tmp files
if [ ! -d /tmp/nginx/body ] ; then
  mkdir -p /tmp/nginx/body
fi
chown $WEB_USER:$WEB_GROUP /tmp/nginx
chown $WEB_USER:$WEB_GROUP /tmp/nginx/body

# Create log directories if they don't exist already
if [ ! -d /var/log/nginx ] ; then
  mkdir -p /var/log/nginx
fi
if [ ! -d /var/log/php ] ; then
  mkdir -p /var/log/php
fi
if [ ! -d /var/log/mail ] ; then
  mkdir -p /var/log/mail
fi

if [ ! -d $WEB_ROOT ] ; then
  mkdir -p $WEB_ROOT
  chown $WEB_USER:$WEB_GROUP $WEB_ROOT
fi

# Give $WEB_USER user access to all log files
chown -R $WEB_USER:$WEB_GROUP /var/log/
