#!/usr/bin/with-contenv bash

# Create uploads directory if not exists
mkdir -p $UPLOADS_ROOT
chown $WEB_USER:$WEB_GROUP $UPLOADS_ROOT

# Create dir for nginx tmp files
mkdir -p /tmp/nginx/body
chown -R $WEB_USER:$WEB_GROUP /tmp/nginx

# Create log directories if they don't exist already
mkdir -p /var/log/{nginx,php,mail}

# Create error.log so that php-fpm can write to it
touch /var/log/php/error.log

# Chown all files to wordpress
chown -R $WEB_USER:$WEB_GROUP /var/log/{nginx,php,mail}
