#!/usr/bin/with-contenv bash

# Setup sessions
echo "; This file contains php session backend (default: files)" > /etc/php/7.0/fpm/conf.d/sessions.ini

if [ "$PHP_SESSION_HANDLER" == "redis" ]; then
  echo "session.save_handler = redis" >> /etc/php/7.0/fpm/conf.d/sessions.ini

  redis_resource_string="$REDIS_SCHEME://"

  # Use different setup in dev/prod
  if [ "$REDIS_HOST" != "" ]; then
    redis_resource_string+="$REDIS_HOST:$REDIS_PORT"
  elif [ "$REDIS_PORT_6379_TCP_ADDR" != "" ]; then
    redis_resource_string+="$REDIS_PORT_6379_TCP_ADDR:$REDIS_PORT"
  fi

  # Use password or different database when user provides them
  redis_resource_string+="?database=$PHP_SESSION_REDIS_DB"

  if [ "$REDIS_PASSWORD" != "" ]; then
    redis_resource_string+="&auth=$REDIS_PASSWORD"
  fi

  echo "session.save_path = \"$redis_resource_string\"" >> /etc/php/7.0/fpm/conf.d/sessions.ini

else # Use normal file based sessions if redis is not configured
    mkdir -p /tmp/php
    chown $WEB_USER:$WEB_GROUP /tmp/php
    echo "session.save_handler = files" >> /etc/php/7.0/fpm/conf.d/sessions.ini
    echo "session.save_path = /tmp/php" >> /etc/php/7.0/fpm/conf.d/sessions.ini
fi
