#!/usr/bin/with-contenv bash

# Give other processes a moment to startup
sleep 2

echo "[services.d] starting logging helpers"

PIDS=
PID_COUNTER=0

# start log helper for all log files in /var/log
for log_file in /var/log/*/*.log; do
    application=$(basename $(dirname $log_file))
    application_length=${#application}
    filename=$(basename $log_file);
    log_type="${filename%.*}"

    log_header=$(printf "[%12s]" "$application $log_type")

    # Start log watcher process
    echo "[services.d] using logging helper for $application/$filename"

    tail -f $log_file | while read line; do echo "$log_header $line"; done &
    PIDS[$PID_COUNTER]=$!

    # Increment PID number
    let "PID_COUNTER++"
done


# Stop all tailing processes when container is stopped
trap "kill ${PIDS[*]}" SIGINT TERM INT

wait
