#!/usr/bin/with-contenv sh
##
# This script uses clever heredoc hack to substitute env variables into static config files
# Source: http://stackoverflow.com/questions/2914220/bash-templating-how-to-build-configuration-files-from-templates-with-bash
##

echo "INFO: Substituting env into configuration files..."

# Nginx doesn't support env variables in config files so we will have to do this in hacky way instead
VARS='$PORT:$WEB_ROOT:$NGINX_INCLUDE_DIR:$NGINX_MAX_BODY_SIZE:$NGINX_FASTCGI_TIMEOUT'
envsubst "$VARS" < /etc/nginx/nginx.conf > /tmp/nginx.conf
mv /tmp/nginx.conf /etc/nginx/nginx.conf

envsubst "$VARS" < /etc/php5/php-fpm.conf > /tmp/php-fpm.conf
mv /tmp/php-fpm.conf /etc/php5/php-fpm.conf
